# Site settings
title: Redstone.dart
name: Redstone.dart
email: luiz.mineo@gmail.com
description: "Redstone.dart website"
baseurl: ""
url: "http://redstonedart.org"

# Github defaults
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty

collections:
  doc:
    output: true
