name: redstone
version: 0.5.11
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A metadata driven microframework for Dart 
homepage: http://redstonedart.org
environment:
  sdk: '>=1.4.0 <2.0.0'
dependencies:
  collection: '>=0.9.3+1 <0.10.0'
  crypto: '>=0.9.0 <0.10.0'
  grinder: '>=0.5.2 <0.6.0'
  route_hierarchical: '>=0.4.21 <0.5.0'
  di: ">=2.0.1 <3.0.0"
  shelf: ">=0.5.4+2 <0.6.0"
  mime: ">=0.9.0+1 <0.10.0"
  http: ">=0.11.1+1 <0.12.0"
  stack_trace: ">=0.9.1 <2.0.0"
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
