name: redstone
version: 0.3.1
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A metadata driven microframework for Dart
homepage: http://luizmineo.github.io/redstone.dart
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  grinder: '>=0.5.2 <0.6.0'
  http_server: '>=0.9.2 <0.10.0'
  route_hierarchical: '>=0.4.20 <0.5.0'
  di: ">=0.0.40 <0.1.0"
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
