name: bloodless
author: Luiz Mineo <luiz.mineo@gmail.com>
version: 0.1.0
description: "A microframework for Dart"
homepage: https://github.com/luizmineo/bloodless
dependencies:
  route_hierarchical: ">=0.4.14 <0.5.0"
  http_server: ">=0.9.1 <0.10.0"
  grinder: ">=0.5.1 <0.6.0"
dev_dependencies:
  unittest: ">=0.9.0 <=0.10.0"